version: "3.9"
services:
  localai:
    image: ghcr.io/mudler/localai:latest
    container_name: localai
    ports:
      - "8080:8080"
    environment:
      - MODELS_PATH=/models
      - THREADS=4
    volumes:
      - ./models:/models
      - ./models.yaml:/models/models.yaml
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage: {}

